### ISSUE TITLE
您好，轻微有youtube-bb数据库吗

### ISSUE THREAD

**Issue by chengxianda54321** [PengBoXiangShang/SiamRPN_plus_plus_PyTorch#10]

**Comment by PengBoXiangShang** [comment]
Sorry, we don't have YouTube BB dataset.

**Comment by chengxianda54321** [comment]
所以你的网络怎么训练呢?------------------ 原始邮件 ------------------
发件人: "Peng Xu"<notifications@github.com>
发送时间: 2019年5月18日(星期六) 晚上7:30
收件人: "PengBoXiangShang/SiamRPN_plus_plus_PyTorch"<SiamRPN_plus_plus_PyTorch@noreply.github.com>;
抄送: "chengxianda54321"<962629514@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PengBoXiangShang/SiamRPN_plus_plus_PyTorch] 您好，轻微有youtube-bb数据库吗 (#10)



Sorry, we don't have YouTube BB dataset.
 
&mdash;
