### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by yeqingQian** [PengBoXiangShang/SiamRPN_plus_plus_PyTorch#6]
您好，您这边要求的Ubuntu 14.04、Python 2.7、PyTorch 0.4.0
我想请教下，我使用Ubuntu 17.10、Python3、PyTorch 0.4的话是否可以？

**Comment by xueqian0110** [comment]
@yeqingQian 我试了一下可以训练，就是把print()函数加上括号。

**Comment by yeqingQian** [comment]
谢谢你，我现在也调通了，然后想问一下作者，测试代码大概什么时候公开，




------------------ 原始邮件 ------------------
发件人: "hujuan940506"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 晚上7:52
收件人: "PengBoXiangShang/SiamRPN_plus_plus_PyTorch"<SiamRPN_plus_plus_PyTorch@noreply.github.com>;
抄送: "集美大学 钱叶青"<1322945036@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [PengBoXiangShang/SiamRPN_plus_plus_PyTorch] 请教 (#6)




@yeqingQian 我试了一下可以训练，就是把print()函数加上括号。

**Comment by KMSZJJ** [comment]
@yeqingQian 你好，请问你有遇到以下情况么？
  File "/Lun1/SiamRPN_plus_plus/dataloader/dataset.py", line 68, in imread
    img_buffer = np.frombuffer(img_buffer, np.uint8)
AttributeError: 'NoneType' object has no attribute '__buffer__'
